import os
import sys
from unittest.mock import patch

import pytest

# Add project root to path so we can import vdeps
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import vdeps


def write_config(root, content):
    (root / "vdeps.toml").write_text(content, encoding="utf-8")


def run_main(root, argv):
    with (
        patch("sys.argv", ["vdeps.py", *argv]),
        patch("vdeps.__file__", str(root / "vdeps.py")),
    ):
        vdeps.main()


def test_generate_cmake_writes_expected_wrapper(tmp_path):
    write_config(
        tmp_path,
        """
[[dependency]]
name = "nvrhi"
rel_path = "nvrhi"
cmake_options = []

[[dependency]]
name = "ShaderMake"
rel_path = "ShaderMake"
cmake_options = []

[[dependency]]
name = "vk-bootstrap"
rel_path = "vk-bootstrap"
cmake_options = []
""",
    )

    with patch("subprocess.run") as mock_run, patch("shutil.copy2") as mock_copy:
        run_main(tmp_path, ["--generate-cmake"])

    generated = tmp_path / "vdeps" / "CMakeLists.txt"
    content = generated.read_text(encoding="utf-8")

    assert content.startswith(
        "# Generated by vdeps.py --generate-cmake\n# Do not edit manually\n"
    )
    assert "# Generated targets always run vdeps.py --build --auto-skip." in content
    assert (
        "# Run vdeps.py manually if you need a forced rebuild or troubleshooting."
        in content
    )
    assert "find_package(Python3 REQUIRED COMPONENTS Interpreter)" in content
    assert 'option(VDEPS_USE_LLVM "Use Clang/LLVM compiler on Windows" OFF)' in content
    assert (
        'option(VDEPS_STATIC_RUNTIME "Build with static MSVC runtime (/MT, /MTd)" OFF)'
        in content
    )
    assert (
        'option(VDEPS_DYNAMIC_RUNTIME "Build with dynamic MSVC runtime (/MD, /MDd)" OFF)'
        in content
    )
    assert "if(NOT VDEPS_STATIC_RUNTIME AND NOT VDEPS_DYNAMIC_RUNTIME)" in content
    assert "set(VDEPS_STATIC_RUNTIME ON)" in content
    assert "macro(vdeps_build_dep" in content
    assert 'separate_arguments(_VDEPS_EXTRA_ARGS NATIVE_COMMAND "${EXTRA_ARGS}")' in content
    assert "${_VDEPS_EXTRA_ARGS}" in content
    assert "--auto-skip ${EXTRA_ARGS}" not in content
    assert "add_custom_target(vdeps_all_mt)" in content
    assert 'vdeps_build_dep(vdeps_nvrhi nvrhi mt "")' in content
    assert 'vdeps_build_dep(vdeps_shadermake ShaderMake mt "")' in content
    assert 'vdeps_build_dep(vdeps_vk_bootstrap vk-bootstrap mt "")' in content
    assert "add_custom_target(vdeps_all)" in content
    assert "add_dependencies(vdeps_all vdeps_all_mt)" in content

    mock_run.assert_not_called()
    mock_copy.assert_not_called()


def test_generate_cmake_rejects_target_name_collisions(tmp_path, capsys):
    write_config(
        tmp_path,
        """
[[dependency]]
name = "foo-bar"
rel_path = "foo-bar"
cmake_options = []

[[dependency]]
name = "foo_bar"
rel_path = "foo_bar"
cmake_options = []
""",
    )

    with pytest.raises(SystemExit) as exc:
        run_main(tmp_path, ["--generate-cmake"])

    assert exc.value.code == 1
    captured = capsys.readouterr()
    assert "CMake target name collision" in captured.out
    assert "foo-bar" in captured.out
    assert "foo_bar" in captured.out
    assert not (tmp_path / "vdeps" / "CMakeLists.txt").exists()


def test_generate_cmake_refuses_to_overwrite_handwritten_file(tmp_path, capsys):
    write_config(
        tmp_path,
        """
[[dependency]]
name = "nvrhi"
rel_path = "nvrhi"
cmake_options = []
""",
    )
    output_dir = tmp_path / "vdeps"
    output_dir.mkdir()
    output_path = output_dir / "CMakeLists.txt"
    output_path.write_text("# handwritten\n", encoding="utf-8")

    with pytest.raises(SystemExit) as exc:
        run_main(tmp_path, ["--generate-cmake"])

    assert exc.value.code == 1
    captured = capsys.readouterr()
    assert "Refusing to overwrite non-generated file" in captured.out
    assert output_path.read_text(encoding="utf-8") == "# handwritten\n"


@pytest.mark.parametrize(
    ("argv", "message"),
    [
        (
            ["--generate-cmake", "--build"],
            "--generate-cmake cannot be used with --build",
        ),
        (
            ["--generate-cmake", "--clean"],
            "--generate-cmake cannot be used with --clean",
        ),
        (
            ["--generate-cmake", "nvrhi"],
            "--generate-cmake cannot be used with dependency names",
        ),
        (["--generate-cmake", "--llvm"], "--generate-cmake cannot be used with --llvm"),
    ],
)
def test_generate_cmake_rejects_invalid_flag_combinations(
    tmp_path, argv, message, capsys
):
    write_config(
        tmp_path,
        """
[[dependency]]
name = "nvrhi"
rel_path = "nvrhi"
cmake_options = []
""",
    )

    with pytest.raises(SystemExit) as exc:
        run_main(tmp_path, argv)

    assert exc.value.code == 2
    captured = capsys.readouterr()
    assert message in captured.err
